### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dirtbikerxz** [username115/FRCScouting#122]
Why is the pull data option grayed out. What would that option do anyway, it would be nice to be able to view all the data from the app itself. And how do i have the database/app interface with the first api so that when the match schedule is released, it will update in the app? I know the is a populate_event_list php file in the server folder, but there is no documentation for it.

**Comment by username115** [comment]
The data lookup button is grayed out because it is not fully implemented. It is intended to be a simple lookup of the data in the database, without any real analysis functionality. You can still export the data to CSV files using the export option in the pop-up menu. These files contain all of the data recorded in the app.

As for event population, the event list script included in the server files is not necessary for normal use. It is included in case you decide you want to update the event list yourself, using your own token. 

Our website utilizes the FIRST API to get schedule updates, and then the app pulls the schedule from our website.

**Comment by dirtbikerxz** [comment]
I chose the palameto regional as the event (because it already happened) but when i hit sync match schedule, it just says no schedule available... why is that?

**Comment by username115** [comment]
I just noticed an issue that would cause problems, though I am getting a schedule for Palmetto (it's what I tested against). It seems that the FIRST API returned bad end dates, which our server scripts use to determine when schedule updates may occur. I will fix this tomorrow, unfortunately I am sick in bed at this time.

**Comment by username115** [comment]
Never mind the end date issue. I misread the table. I will look into why you are not getting schedule updates tomorrow.

**Comment by dirtbikerxz** [comment]
That's absolutley fine :D. Our first regional isnt for another 12 days so thats fine too :D. So in the database folder all i have to include are scouting.php and scouting header.php right, just don't even bother uploading the populate_event_list.php? Also, I'm hoping to use tableau to analyze the data. Do you know a way of how i can set it so that it read's that cross rock wall is a 0 (in pit scouting) and automatically make a list of what defenses a robot can't cross?

**Comment by dirtbikerxz** [comment]
Correction. I had accidentally put the app in match scouting, that's why i wasn't getting the team's list. However one problem i am having is getting the robot pics. What am I supposed to be doing to see the robot pics? I have the pics uploaded on the database, and everything set up as the readme says.

**Comment by username115** [comment]
I've never used Tableau, so I would not be able to give any insight there.

I'm glad the schedule works for you. I just tested it with the San Diego Regional, and it does work.
Early last year, they did publish practice match schedules, but it was removed midway through the season.

For robot pictures, as long as the database is synced on the phone, it should pull whatever url is specified in the robot_lu table to display the picture. Pictures will display automatically if the team number is filled in via match schedule, but you can tell it to manually load a team's picture by tapping the picture on the Match Start screen.

**Comment by dirtbikerxz** [comment]
Oh, I realised why the robotpics weren't loading. In populate_robot_pics.php, i had to put http:// before the url to the directory. You should include that tip in the readme just so other don't get confused like I did. :D So, do you have a approimate date on when you will be able to release and update that will enable the lookup data function? I know it dosen't have any analysis, but it would be nice to have a easy way for people to access all the raw data of a specific team straight from their phones. If you are not able to, I'm thinking of maybe building a site that will allow access to the data, I don't know. Thanks again a lot for all the hard work, and please let me know the status on the "data lookup" button. Thanks!!

**Comment by username115** [comment]
That will be the next thing I work on. Hopefully there will be something in the next few weeks, I tend to spend a good portion of competitions working on this in the stands, and our first district is next weekend.

**Comment by dirtbikerxz** [comment]
Cool. Our first regional is the Bayou Regional (march 17th-ish). So, I'll attempt to make something that will do that just in case you don't have the time to finish before than, but I hope that it'll be done by then, this app is really amazing and implemented REALLY well. Thank You for all your work, and looking forward to it!! :D

**Comment by username115** [comment]
Closing this issue, nothing to be updated that wasn't covered by other issues
