### ISSUE TITLE
Possible New Feature?

### ISSUE THREAD

**Issue by dirtbikerxz** [username115/FRCScouting#126]
In pit scouting, is it possible to have a window which lists all the teams of that regional, and a tiny check mark or x mark next to each team indication if that team had been scouted yet. Just simply check the database for an entry on the team number and if something exists just display a check mark. (like it already does when you type in a number manually, if there is already data for the team it says "do you want to load data", same concept right?)

**Comment by username115** [comment]
Already have a similar issue open in #55 . Marking this one as duplicate. You can add your comments to that one.
