### ISSUE TITLE
IOS Version?

### ISSUE THREAD

**Issue by dirtbikerxz** [username115/FRCScouting#133]
Hey, So first of all, I just wanted to thank you. Once I figured out the whole mysql database side, this app was a god send. So many people loved it, and there is so much I can do with it.

Anyway, I just wanted to ask, will there ever be an IOS version of the app? More than 70 percent of the teams have iphones, and right now they have to use old clunky android tablets to scout.

**Comment by username115** [comment]
At this time, there are no plans for an iOS version, unless somebody else wants to write it. Unfortunately, I do not have the time available to support both platforms on this app. Our team has enough Android phones to make this possible, the students use their own or let other students borrow them.

For the Android version, however, if you are struggling with any particular aspect of the app or server, feel free to let me know and I would be happy to provide guidance and troubleshooting help.
