### ISSUE TITLE
Possible issue with DB Sync failed due to missing timezone setting

### ISSUE THREAD

**Issue by dachaeon** [username115/FRCScouting#163]
I am not sure if this is going to be a general problem or if it is due to my strange setup (apache on OSX with mod_php).

I dug into the debug settings and added some logging to find that my db syncs were returning some html with error messages rather than valid JSON.

Adding the following method near the beginning of my scouting.php file resolved the issue for me:
date_default_timezone_set('US/Central');

**Comment by username115** [comment]
This seems like a setup issue to me. Timezone should be set by your system ini settings, and only changed when required in each script that needs something different from the system.

[http://php.net/manual/en/function.date-default-timezone-set.php](url)

> Instead of using this function to set the default timezone in your script, you can also use the INI setting date.timezone to set the default timezone.

**Comment by dachaeon** [comment]
good to know - thanks for the info!

**Comment by username115** [comment]
Happy to field the question. Don't hesitate to submit issues as you find them.
