### ISSUE TITLE
App crashes in Data Lookup

### ISSUE THREAD

**Issue by Dnarok** [username115/FRCScouting#182]
By clicking on a team's number, and pressing the back button, and repeating this action, eventually the app will crash. Usually happens in 3-10 attempts, and occurs regardless of time spent in the app.

**Comment by username115** [comment]
After looking into this, I believe that it might be cause by a callback going to the Pit Data Fragment after the fragment has been destroyed. Need to ad handling that checks to see if the fragment is still being displayed.
